# Generated by Django 4.2.5 on 2023-09-09 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='publicada',
            new_name='publicar',
        ),
    ]
